micronaut:
  server:
    port: 8080
  application:
    name: oauth
  security:
    authentication: idtoken
    oauth2:
      clients:
        okta:
          client-secret: '*********************************************************'
          client-id: '**************'
          openid:
            issuer: 'https://dev-12345.okta.com/oauth2/default'
    endpoints:
      logout:
        get-allowed: true
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

netty:
  default:
    allocator:
      max-order: 3
